swagger: "2.0"
info:
  title: Chotube Media Server
  description: Trabajo practico de taller 2.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https

paths:
  /videos:
    get:
      summary: Returns a list of videos.
      responses:
        200:
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string